version: '3.3'
services:
  nginx: 
    image: joaovagner/nginx:latest
    build:
      context: docker/nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web

  web:
    image: joaovagner/web:latest
    build: 
      context: docker/app
    ports:
      - 8000:8000
    
